export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILED  = "REGISTER_FAILED"
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAILED = "CREATE_PROJECT_FAILED";
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const CREATE_TASK_FAILED = "CREATE_TASK_FAILED";
export const TASK_DELETE_SUCCESS = "TASK_DELETE_SUCCESS"
export const TASK_DELETE_FAILED = "TASK_DELETE_FAILED"
